# Generated by Django 4.1.7 on 2023-03-14 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_post_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('coding', 'coding'), ('sports', 'sports'), ('entertainment', 'entertainment')], max_length=200),
        ),
    ]
