# Generated by Django 4.1.7 on 2023-03-15 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_category_name_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.IntegerField(choices=[('publish', 'publish'), ('draft', 'draft')], default='draft'),
        ),
    ]
