# Generated by Django 4.1.7 on 2023-03-24 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_post_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='article_snippet',
            field=models.CharField(default='Click link below to read blog post', max_length=255),
        ),
    ]
