# Generated by Django 4.1.7 on 2023-03-26 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_post_article_snippet'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.AlterField(
            model_name='post',
            name='article_snippet',
            field=models.CharField(max_length=255),
        ),
    ]
