# Generated by Django 4.1.7 on 2023-03-26 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='title',
            new_name='name',
        ),
    ]
