# Generated by Django 4.1.7 on 2023-03-28 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_profile_profile_pic_profile_facebook_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='website_url',
            new_name='Github_url',
        ),
    ]
